In [1]:
import pandas as pd
import numpy as np

# Charger les deux fichiers CSV dans des DataFrames
file1 = "new_data-cleaning.csv"
file2 = "new_data_fake-cleaning22.csv"
df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)

# Concaténer les deux DataFrames
df = pd.concat([df1, df2], ignore_index=True)

In [2]:
df.head()

Unnamed: 0                                            Title  \
0           0  The Georgia Indictment Offers the Whole Picture   
1           1   Sam Bankman-Fried Pushed One Boundary Too Many   
2           2                         Schrödinger’s Cage Match   
3           3      I Turned My House into a Zero-Carbon Utopia   
4           4  The Greatest Pogo Stick the World Has Ever Seen   

                                         Description  Label  
0  articl featur one stori read today newslett ed...      1  
1  updat 1 35 p et august 15 2023 edit atlant dai...      1  
2  follow news earlier today elon musk further na...      1  
3  last april decid break ga compani like mani fo...      1  
4  swelter heat downtown pittsburgh last friday j...      1

In [3]:
df=df.drop("Unnamed: 0",axis=1)

In [4]:
df=df.iloc[np.random.permutation(df.index)].reset_index(drop=True)##df shuffled
df.head()

Title  \
0   BREAKING: Evidence Trump Cheated Leads To MAS...   
1                Paleotsunamis Offer a Quiet Warning   
2  Ukrainians Are Defending the Values Americans ...   
3   DESPERATE Senate Republicans Just Dropped Pro...   
4   Meet The Billionaire Behind Trump’s Twitter B...   

                                         Description  Label  
0  evid uncov could point donald trump russian ri...      0  
1  articl origin publish hakai magazin boulder we...      1  
2  busi go ukrain countri need anoth report cover...      1  
3  matter much want admit true mani republican es...      0  
4  one gop biggest donor use associ ibm man respo...      0

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_v = TfidfVectorizer()
X = tfidf_v.fit_transform(df['Description'])##.values.astype('U')
y = df['Label']

In [6]:
# Convert X_train and X_test from sparse matrix to dense numpy array
#X_train = X_train.toarray()
#X_test = X_test.toarray()

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=40)

In [8]:

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
# Création du modèle Random Forest
RFC = RandomForestClassifier(n_estimators=100, random_state=42)

In [11]:
# Entraînement du modèle
RFC.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = RFC.predict(X_test)
# Évaluation des performances
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

Accuracy: 0.9944792973651192
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1956
           1       1.00      0.99      0.99      2029

    accuracy                           0.99      3985
   macro avg       0.99      0.99      0.99      3985
weighted avg       0.99      0.99      0.99      3985

Confusion Matrix:
[[1953    3]
 [  19 2010]]


In [12]:
# plot confusion matrix
#import matplotlib.pyplot as plt
#import seaborn as sns
#cm = confusion_matrix(y_test, y_pred)
#sns.heatmap(cm, annot=True, cmap='Blues', fmt='g', xticklabels=['0:Fake', '1:Real'], yticklabels=['0:Fake', '1:Real'])
#plt.xlabel('Predicted Class')
#plt.ylabel('True Class')
#plt.title('Confusion Matrix')
#plt.show()

In [13]:
from sklearn.tree import DecisionTreeClassifier

# initialize the decision tree classifier
dtc = DecisionTreeClassifier(random_state=42)
# fit the model on the training data
dtc.fit(X_train, y_train)
# make predictions on the test data
y_pred = dtc.predict(X_test)
# calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy score:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

Accuracy score: 0.9756587202007528
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1956
           1       0.98      0.97      0.98      2029

    accuracy                           0.98      3985
   macro avg       0.98      0.98      0.98      3985
weighted avg       0.98      0.98      0.98      3985

Confusion Matrix:
[[1918   38]
 [  59 1970]]


In [14]:
from sklearn import metrics
from sklearn.linear_model import PassiveAggressiveClassifier
PAclassifier = PassiveAggressiveClassifier(max_iter=1000)
PAclassifier.fit(X_train, y_train)
pred_pac = PAclassifier.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score)
print("Classification Report:")
print(classification_report(y_test, y_pred))
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

accuracy:   0.976
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1956
           1       0.98      0.97      0.98      2029

    accuracy                           0.98      3985
   macro avg       0.98      0.98      0.98      3985
weighted avg       0.98      0.98      0.98      3985

Confusion Matrix:
[[1918   38]
 [  59 1970]]


In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
# Création du modèle de régression logistique pour la classification
lr= LogisticRegression(max_iter=1000, random_state=42)

# Entraînement du modèle
lr.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = lr.predict(X_test)

# Évaluation des performances
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

Accuracy: 0.9854454203262233
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1956
           1       0.99      0.99      0.99      2029

    accuracy                           0.99      3985
   macro avg       0.99      0.99      0.99      3985
weighted avg       0.99      0.99      0.99      3985

Confusion Matrix:
[[1928   28]
 [  30 1999]]


In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
# Création du modèle KNN pour la classification (avec k=5 voisins)
KN = KNeighborsClassifier(n_neighbors=5)

# Entraînement du modèle
KN.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = KN.predict(X_test)

In [19]:
# Évaluation des performances
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

Accuracy: 0.9377666248431619
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.91      0.93      1956
           1       0.92      0.97      0.94      2029

    accuracy                           0.94      3985
   macro avg       0.94      0.94      0.94      3985
weighted avg       0.94      0.94      0.94      3985

Confusion Matrix:
[[1774  182]
 [  66 1963]]


In [35]:
import pickle
pickle.dump(dtc,open('DecisionTree.pkl','wb'))
pickle.dump(lr,open('LogisticRegression.pkl','wb'))
pickle.dump(PAclassifier ,open('PassiveAggressiveClassifier.pkl','wb'))
pickle.dump(RFC,open('RandomForestClassifier.pkl','wb'))
pickle.dump(KN,open('KNeighborsClassifier.pkl','wb'))
pickle.dump(tfidf_v,open('tfidf_v.pkl','wb'))

In [23]:
#test evaluation
#test evaluation
#test_news_df = pd.read_csv('Real_newsTesting-cleaning.csv')
#test_news_df["Label"]=1
#test_tfidf= tfidf_v .transform(test_news_df["article"])

In [24]:
#predictions = lr.predict(test_tfidf)
#print(predictions)
#score= accuracy_score(test_news_df["Label"],predictions)
#print(score)

[1 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1]
0.7083333333333334


In [25]:
#predictions = RFC.predict(test_tfidf)
#print(predictions)
#score= accuracy_score(test_news_df["Label"],predictions)
#print(score)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.9722222222222222


In [26]:
#predictions = dtc.predict(test_tfidf)
#print(predictions)
#score= accuracy_score(test_news_df["Label"],predictions)
#print(score)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.9722222222222222


In [27]:
#predictions = PAclassifier.predict(test_tfidf)
#print(predictions)
#score= accuracy_score(test_news_df["Label"],predictions)
#print(score)

[1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1]
0.7916666666666666


In [28]:
#predictions = KN.predict(test_tfidf)
#print(predictions)
#score= accuracy_score(test_news_df["Label"],predictions)
#print(score)

[0 1 1 1 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1]
0.7777777777777778


In [ ]:
##TEST FAKE NEWS

In [37]:
#test evaluation
#test evaluation
#test_news_df = pd.read_csv('FAKE_newsTesting.csv')
#test_news_df["Label"]=0
#test_news_df.head()
#test_tfidf= tfidf_v .transform(test_news_df["text"])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1.0


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0.9722222222222222


[0 1 0 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1
 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 0]
0.4027777777777778


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1.0


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
0.9861111111111112
